### ISSUE TITLE
no * added

### ISSUE THREAD

**Issue by borkie** [peterflynn/reasonable-comments#4] opened 2013-11-27 23:05 UTC
Does not work, i can't get \* at the beginning of lines

**Comment by peterflynn** [comment] 2014-01-24 00:41
@borkie Can you provide a code sample that shows this problem?

**Comment by gmaggio** [comment] 2014-01-24 04:19
I'm also experiencing the same problem. It's just not working. No automatic asterisk sign (*) generated upon enter.

```
/**
 * Template Name: Frontpage
 */
```

**Comment by peterflynn** [comment] 2014-01-24 19:31
@bedex78 What type of file is this code in?  Also, where are you placing the cursor when your hit enter?

**Comment by gmaggio** [comment] 2014-01-25 01:06
I tried it both in **CSS** and **PHP** files. Both doesn't work. The cursor is **behind the last asterisk**, just after `/**`.

**Comment by peterflynn** [comment] 2014-01-25 01:25
Aha, that explains it -- the extension is currently enabled only for JS code, so this is basically a dupe of issue #1.  I'll get a fix up later this weekend.  Sorry for the confusion!

**Closed as completed by peterflynn** 2014-01-25 01:25 UTC
